/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BatimentChoix: typeof import('./src/components/BatimentChoix.vue')['default']
    BatimentParcelleChoix: typeof import('./src/components/BatimentParcelleChoix.vue')['default']
    copy: typeof import('./src/components/ParcelleChoix copy.vue')['default']
    ObjetChoix: typeof import('./src/components/ObjetChoix.vue')['default']
    ParcelleChoix: typeof import('./src/components/ParcelleChoix.vue')['default']
    RueChoix: typeof import('./src/components/RueChoix.vue')['default']
  }
}
